version: "2"

services:
  workstation-2:
    image: registry.training.local/workstation-2:${IMAGE_VERSION}
    network_mode: bridge
    environment:
      - "SERVICE_NAME=spiffy"
    ports:
      - "4567"

